# Generated by Django 3.1.2 on 2020-10-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0002_remove_qnamodel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnamodel',
            name='docfile',
            field=models.FileField(default="No files", upload_to='document/upload/'),
            preserve_default=False,
        ),
    ]
