# Generated by Django 3.1.2 on 2020-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnamodel',
            name='docfile',
            field=models.FileField(default='No files', upload_to='document/upload/'),
        ),
    ]
