# Generated by Django 3.1.2 on 2020-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0004_auto_20201003_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnamodel',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='qnamodel',
            name='author',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qnamodel',
            name='docfile',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qnamodel',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
