# Generated by Django 3.1.2 on 2020-10-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0005_auto_20201003_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnamodel',
            old_name='created_date',
            new_name='pub_date',
        ),
    ]
