# Generated by Django 3.1.2 on 2020-10-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0006_auto_20201003_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnamodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='qnamodel',
            name='docfile',
        ),
    ]
