# Generated by Django 3.1.2 on 2020-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0006_auto_20201004_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnamodel',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
