# Generated by Django 3.1.2 on 2020-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0011_auto_20201017_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnamodel',
            name='docfile',
            field=models.FileField(default='', upload_to='document/upload/'),
        ),
    ]
