# Generated by Django 3.1.2 on 2020-10-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
