# Generated by Django 3.1.2 on 2020-11-13 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0015_auto_20201023_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='qnamodel',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
