# Generated by Django 3.1.2 on 2020-11-13 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0016_auto_20201113_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='qnamodel',
            name='body',
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
