# Generated by Django 3.1.2 on 2020-11-13 09:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0018_auto_20201113_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='qnamodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
