# Generated by Django 3.1.2 on 2020-11-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_app', '0021_auto_20201124_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QnA_app.category')),
            ],
            options={
                'unique_together': {('category_name',)},
            },
        ),
        migrations.AddField(
            model_name='qnamodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QnA_app.category'),
        ),
    ]
