# Generated by Django 3.1.2 on 2020-12-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Write_mentoring',
            new_name='Write_list',
        ),
    ]
